expense_map = {"Groceries": ["MART", "TARGET", "JEWEL OSCO", "WALGREENS", "Market", "Patel"],
               "Utilities": ["ATT", "CITY OF CRYSTAL LAKE", "Nicor Gas", "COMED",
                             "RECYCLING", "RING"],
               "Entertainment": ["Peacock", "AMC", "Netflix", "Hulu", "Bowlero"],
               "Restaurants": ["Ramen", "Biryani", "Pizza", "Taco", "Chipotle", "Subway",
                               "Annapurna", "Starbucks", "Eggholic"],
               "Car": ["Thornton", "STATE FARM", "Avis"],
               "Travel": ["Frontier", "Etihad", "American", "United", "Ventra", "Metra", "Uber",
                          "Spothero"],
               "Home": ["Home Depot", "Lowe", "Menards", "Woodlore Estates"]}
